# Generated by Django 3.2.8 on 2021-12-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_auto_20211216_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(max_length=200, verbose_name='Slug'),
        ),
    ]
